<?php

namespace Database\Seeders;

use App\Models\AudioFormats;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AudioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $extension_encoding_map = [
        //     '3g2' => 'libx264',
        //     '3gp' => 'libx264',
        //     'a64' => 'rawvideo',
        //     'ac3' => 'ac3',
        //     'adts' => 'aac',
        //     'adx' => 'adx',
        //     'aiff' => 'pcm_s16be',
        //     'alaw' => 'pcm_alaw',
        //     'alp' => 'pcm_alaw',
        //     'alsa' => 'pcm_s16le',
        //     'amr' => 'libopencore_amrnb',
        //     'amv' => 'amv',
        //     'apm' => 'apng',
        //     'apng' => 'apng',
        //     'aptx' => 'aptx',
        //     'aptx_hd' => 'aptx_hd',
        //     'argo_asf' => 'asf',
        //     'argo_cvg' => 'cavsvideo',
        //     'asf' => 'asf',
        //     'asf_stream' => 'asf',
        //     'ass' => 'ass',
        //     'ast' => 'ast',
        //     'au' => 'au',
        //     'avi' => 'avi',
        //     'avif' => 'av1',
        //     'avm2' => 'flv',
        //     'avs2' => 'avs2',
        //     'avs3' => 'avs3',
        //     'bit' => 'bit',
        //     'caca' => 'caca',
        //     'caf' => 'caf',
        //     'cavsvideo' => 'cavsvideo',
        //     'chromaprint' => 'chromaprint',
        //     'codec2' => 'codec2',
        //     'codec2raw' => 'codec2raw',
        //     'crc' => 'crc',
        //     'dash' => 'dash',
        //     'data' => 'data',
        //     'daud' => 'daud',
        //     'dfpwm' => 'dfpwm',
        //     'dirac' => 'dirac',
        //     'dnxhd' => 'dnxhd',
        //     'dts' => 'dts',
        //     'dv' => 'dvvideo',
        //     'dvd' => 'mpeg2video',
        //     'eac3' => 'eac3',
        //     'EOF4mpegpipe' => 'mpeg4',
        //     'f32be' => 'pcm_f32be',
        //     'f32le' => 'pcm_f32le',
        //     'f4v' => 'libx264',
        //     'f64be' => 'pcm_f64be',
        //     'f64le' => 'pcm_f64le',
        //     'fbdev' => 'fbdev',
        //     'ffmetadata' => 'ffmetadata',
        //     'fifo' => 'fifo',
        //     'fifo_test' => 'fifo_test',
        //     'film_cpk' => 'film_cpk',
        //     'filmstrip' => 'filmstrip',
        //     'fits' => 'fits',
        //     'flac' => 'flac',
        //     'flv' => 'flv',
        //     'framecrc' => 'framecrc',
        //     'framehash' => 'framehash',
        //     'framemd5' => 'framemd5',
        //     'g722' => 'g722',
        //     'g723_1' => 'g723_1',
        //     'g726' => 'g726',
        //     'g726le' => 'g726le',
        //     'gif' => 'gif',
        //     'gsm' => 'gsm',
        //     'gxf' => 'gxf',
        //     'h261' => 'h261',
        //     'h263' => 'h263',
        //     'h264' => 'h264',
        //     'hash' => 'hash',
        //     'hds' => 'hds',
        //     'hevc' => 'hevc',
        //     'hls' => 'hls',
        //     'ico' => 'ico',
        //     'idf' => 'idf',
        //     'ilbc' => 'ilbc',
        //     'image2' => 'image2',
        //     'image2pipe' => 'image2pipe',
        //     'ipod' => 'ipod',
        //     'ircam' => 'ircam',
        //     'ismv' => 'ismv',
        //     'ivf' => 'ivf',
        //     'jacosub' => 'jacosub',
        //     'kvag' => 'kvag',
        //     'latm' => 'latm',
        //     'lrc' => 'lrc',
        //     'm4v' => 'm4v',
        //     'matroska' => 'matroska',
        //     'md5' => 'md5',
        //     'microdvd' => 'microdvd',
        //     'mjpeg' => 'mjpeg',
        //     'mkvtimestamp_v2' => 'mkvtimestamp_v2',
        //     'mlp' => 'mlp',
        //     'mmf' => 'mmf',
        //     'mov' => 'mov',
        //     'mp2' => 'mp2',
        //     'mp3' => 'mp3',
        //     'mp4' => 'mp4',
        //     'mpeg' => 'mpeg',
        //     'mpeg1video' => 'mpeg1video',
        //     'mpeg2video' => 'mpeg2video',
        //     'mpegts' => 'mpegts',
        //     'mpjpeg' => 'mpjpeg',
        //     'mulaw' => 'mulaw',
        //     'mxf' => 'mxf',
        //     'mxf_d10' => 'mxf_d10',
        //     'mxf_opatom' => 'mxf_opatom',
        //     'null' => 'null',
        //     'nut' => 'nut',
        //     'obu' => 'obu',
        //     'oga' => 'oga',
        //     'ogg' => 'ogg',
        //     'ogv' => 'ogv',
        //     'oma' => 'oma',
        //     'opengl' => 'opengl',
        //     'opus' => 'opus',
        //     'oss' => 'oss',
        //     'psp' => 'psp',
        //     'pulse' => 'pulse',
        //     'r3d' => 'r3d',
        //     'rawvideo' => 'rawvideo',
        //     'rm' => 'rm',
        //     'roq' => 'roq',
        //     'rso' => 'rso',
        //     'rtp' => 'rtp',
        //     'rtp_mpegts' => 'rtp_mpegts',
        //     'rtsp' => 'rtsp',
        //     's16be' => 's16be',
        //     's16le' => 's16le',
        //     's24be' => 's24be',
        //     's24le' => 's24le',
        //     's32be' => 's32be',
        //     's32le' => 's32le',
        //     's337m' => 's337m',
        //     's8' => 's8',
        //     'sap' => 'sap',
        //     'sbc' => 'sbc',
        //     'scc' => 'scc',
        //     'sdl,sdl2' => 'sdl,sdl2',
        //     'segment' => 'segment',
        //     'smjpeg' => 'smjpeg',
        //     'smoothstreaming' => 'smoothstreaming',
        //     'sox' => 'sox',
        //     'spdif' => 'spdif',
        //     'spx' => 'spx',
        //     'srt' => 'srt',
        //     'stream_segment,s' => 'stream_segment,s',
        //     'streamhash' => 'streamhash',
        //     'sup' => 'sup',
        //     'svcd' => 'svcd',
        //     'swf' => 'swf',
        //     'tee' => 'tee',
        //     'truehd' => 'truehd',
        //     'tta' => 'tta',
        //     'ttml' => 'ttml',
        //     'u16be' => 'u16be',
        //     'u16le' => 'u16le',
        //     'u24be' => 'u24be',
        //     'u24le' => 'u24le',
        //     'u32be' => 'u32be',
        //     'u32le' => 'u32le',
        //     'u8' => 'u8',
        //     'uncodedframecrc' => 'uncodedframecrc',
        //     'vc1' => 'vc1',
        //     'vc1test' => 'vc1test',
        //     'vcd' => 'vcd',
        //     'vidc' => 'vidc',
        //     'video4linux2' => 'video4linux2',
        //     'vob' => 'vob',
        //     'voc' => 'voc',
        //     'w64' => 'w64',
        //     'wav' => 'wav',
        //     'webm' => 'webm',
        //     'webp' => 'webp',
        //     'webvtt' => 'webvtt',
        //     'wsaud' => 'wsaud',
        //     'wtv' => 'wtv',
        //     'wv' => 'wv',
        //     'xv' => 'xv',
        //     'yuv4mpegpipe' => 'yuv4mpegpipe',
        // ];
        $formats = [
            "3g2",
            "3gp",
            "a64",
            "ac3",
            "adts",
            "adx",
            "aiff",
            "alaw",
            "alp",
            "alsa",
            "amr",
            "amv",
            "apm",
            "apng",
            "aptx",
            "aptx_hd",
            "argo_asf",
            "argo_cvg",
            "asf",
            "asf_stream",
            "ass",
            "ast",
            "au",
            "avi",
            "avif",
            "avm2",
            "avs2",
            "avs3",
            "bit",
            "caca",
            "caf",
            "cavsvideo",
            "chromaprint",
            "codec2",
            "codec2raw",
            "crc",
            "dash",
            "data",
            "daud",
            "dfpwm",
            "dirac",
            "dnxhd",
            "dts",
            "dv",
            "dvd",
            "eac3",
            "EOF4mpegpipe",
            "f32be",
            "f32le",
            "f4v",
            "f64be",
            "f64le",
            "fbdev",
            "ffmetadata",
            "fifo",
            "fifo_test",
            "film_cpk",
            "filmstrip",
            "fits",
            "flac",
            "flv",
            "framecrc",
            "framehash",
            "framemd5",
            "g722",
            "g723_1",
            "g726",
            "g726le",
            "gif",
            "gsm",
            "gxf",
            "h261",
            "h263",
            "h264",
            "hash",
            "hds",
            "hevc",
            "hls",
            "ico",
            "idf",
            "ilbc",
            "image2",
            "image2pipe",
            "ipod",
            "ircam",
            "ismv",
            "ivf",
            "jacosub",
            "kvag",
            "latm",
            "lrc",
            "m4v",
            "matroska",
            "md5",
            "microdvd",
            "mjpeg",
            "mkvtimestamp_v2",
            "mlp",
            "mmf",
            "mov",
            "mp2",
            "mp3",
            "mp4",
            "mpeg",
            "mpeg1video",
            "mpeg2video",
            "mpegts",
            "mpjpeg",
            "mulaw",
            "mxf",
            "mxf_d10",
            "mxf_opatom",
            "null",
            "nut",
            "obu",
            "oga",
            "ogg",
            "ogv",
            "oma",
            "opengl",
            "opus",
            "oss",
            "psp",
            "pulse",
            "r3d",
            "rawvideo",
            "rm",
            "roq",
            "rso",
            "rtp",
            "rtp_mpegts",
            "rtsp",
            "s16be",
            "s16le",
            "s24be",
            "s24le",
            "s32be",
            "s32le",
            "s337m",
            "s8",
            "sap",
            "sbc",
            "scc",
            "sdl,sdl2",
            "segment",
            "smjpeg",
            "smoothstreaming",
            "sox",
            "spdif",
            "spx",
            "srt",
            "stream_segment,s",
            "streamhash",
            "sup",
            "svcd",
            "swf",
            "tee",
            "truehd",
            "tta",
            "ttml",
            "u16be",
            "u16le",
            "u24be",
            "u24le",
            "u32be",
            "u32le",
            "u8",
            "uncodedframecrc",
            "vc1",
            "vc1test",
            "vcd",
            "vidc",
            "video4linux2",
            "vob",
            "voc",
            "w64",
            "wav",
            "webm",
            "webp",
            "webvtt",
            "wsaud",
            "wtv",
            "wv",
            "xv",
            "yuv4mpegpipe",
        ];
        foreach ($formats as $format) {
            AudioFormats::create([
                'extension' => strtolower($format),
                'name' => $format,
                // 'encoding' => $value,
            ]);
        }
    }
}
