<?php

namespace Database\Seeders;

use App\Models\Format;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FormatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $formats = [
            // "3FR",
            // "3G2",
            // "3GP",
            "AAI",
            "AI",
            "APNG",
            "ART",
            // "ARW",
            // "AVI",
            // "AVIF",
            "AVS",
            "BGR",
            "BGRA",
            "BGRO",
            "BIE",
            "BMP",
            "BMP2",
            "BMP3",
            "BRF",
            "CAL",
            "CALS",
            // "CANVAS",
            // "CAPTION",
            "CIN",
            "CIP",
            // "CLIP",
            "CMYK",
            "CMYKA",
            // "CR2",
            // "CR3",
            // "CRW",
            // "CUR",
            // "CUT",
            // "DATA",
            // "DCM",
            // "DCR",
            "DCX",
            "DDS",
            // "DFONT",
            // "DJVU",
            // "DNG",
            // "DOT",
            "DPX",
            "DXT1",
            "DXT5",
            "EPDF",
            "EPI",
            // "EPS",
            "EPS2",
            "EPS3",
            "EPSF",
            "EPSI",
            // "EPT",
            "EPT2",
            "EPT3",
            // "ERF",
            "EXR",
            "FAX",
            // "FILE",
            "FITS",
            // "FRACTAL",
            // "FTP",
            "FTS",
            "G3",
            "G4",
            "GIF",
            "GIF87",
            // "GRADIENT",
            "GRAY",
            "GRAYA",
            // "GROUP4",
            // "GV",
            "H",
            // "HALD",
            "HDR",
            // "HEIC",
            // "HISTOGRAM",
            "HRZ",
            "HTM",
            "HTML",
            // "HTTP",
            // "HTTPS",
            "ICB",
            // "ICO",
            // "ICON",
            // "IIQ",
            "INFO",
            // "INLINE",
            // "IPL",
            "ISOBRL",
            "ISOBRL6",
            "J2C",
            "J2K",
            "JBG",
            "JBIG",
            "JNG",
            "JNX",
            "JP2",
            "JPC",
            "JPE",
            "JPEG",
            "JPG",
            "JPM",
            "JPS",
            // "JPT",
            "JSON",
            // "K25",
            // "KDC",
            // "LABEL",
            "M2V",
            "M4V",
            // "MAC",
            "MAGICK",
            "MAP",
            // "MASK",
            "MAT",
            "MATTE",
            // "MEF",
            "MIFF",
            "MKV",
            "MNG",
            "MONO",
            "MOV",
            "MP4",
            "MPC",
            "MPG",
            // "MRW",
            // "MSL",
            // "MSVG",
            "MTV",
            // "MVG",
            // "NEF",
            // "NRW",
            // "NULL",
            // "ORF",
            // "OTB",
            "OTF",
            "PAL",
            "PALM",
            "PAM",
            // "PANGO",
            // "PATTERN",
            "PBM",
            "PCD",
            "PCDS",
            "PCL",
            "PCT",
            "PCX",
            "PDB",
            // "PDF",
            "PDFA",
            // "PEF",
            // "PES",
            // "PFA",
            // "PFB",
            "PFM",
            "PGM",
            "PGX",
            // "PICON",
            "PICT",
            // "PIX",
            "PJPEG",
            // "PLASMA",
            "PNG",
            "PNG00",
            "PNG24",
            "PNG32",
            "PNG48",
            "PNG64",
            "PNG8",
            "PNM",
            // "POCKETMOD",
            "PPM",
            // "PREVIEW",
            // "PS",
            // "PS2",
            // "PS3",
            "PSB",
            "PSD",
            "PTIF",
            // "PWP",
            // "RADIAL-GRADIENT",
            // "RAF",
            "RAS",
            // "RAW",
            "RGB",
            "RGBA",
            "RGBO",
            // "RGF",
            // "RLA",
            // "RLE",
            // "RMF",
            // "RW2",
            // "SCR",
            // "SCT",
            // "SFW",
            "SGI",
            "SHTML",
            "SIX",
            "SIXEL",
            "SPARSE-COLOR",
            // "SR2",
            // "SRF",
            // "STEGANO",
            "SUN",
            // "SVG",
            // "SVGZ",
            // "TEXT",
            "TGA",
            // "THUMBNAIL",
            "TIFF",
            "TIFF64",
            // "TILE",
            // "TIM",
            // "TTC",
            // "TTF",
            "TXT",
            "UBRL",
            "UBRL6",
            "UIL",
            "UYVY",
            "VDA",
            "VICAR",
            // "VID",
            // "VIDEO",
            "VIFF",
            "VIPS",
            "VST",
            "WBMP",
            "WEBM",
            "WEBP",
            // "WMF",
            "WMV",
            // "WMZ",
            // "WPG",
            // "X",
            // "X3F",
            "XBM",
            // "XC",
            // "XCF",
            "XPM",
            // "XPS",
            "XV",
            "XWD",
            "YCbCr",
            "YCbCrA",
            "YUV"
        ];

        foreach ($formats as $format) {
            Format::create([
                'extension' => strtolower($format),
                'name' => $format
            ]);
        }
    }
}
